spring:
  application:
    name: service-reset-password

server:
  port: 8188

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost