spring:
  application:
    name: service-walistudi

server:
  port: 8183

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost