spring:
  application:
    name: service-id-generator

server:
  port: 8189

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost