spring:
  application:
    name: service-registrasi-matakuliah

server:
  port: 8191

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost