spring:
  application:
    name: service-login-detail

server:
  port: 8187

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost